language: go

go:
  - 1.6.2
sudo: required
#install:
#  - go get github.com/bmizerany/assert
# docker: docker run -it --rm -v "$(pwd)":/home/travis mgruener/travis-cli
# travis encrypt -r jlandure/cf-go-info --add deploy.password
deploy:
   edge: true
   provider: cloudfoundry
   username: hmnafie@free.fr
   password: Hicham55@                                                                                                                                                                                                                                         
   api: https://api.run.pivotal.io
   organization: pivotaledu
   space: production
